### ISSUE TITLE
Update needed to latest netlink library

### ISSUE THREAD

**Issue by dstiliadis** [ti-mo/conntrack#10]
It seems that the netlink library slightly changed it's APIs and the master cannot build any more. PR to fix this here: https://github.com/ti-mo/conntrack/pull/9

**Comment by ti-mo** [comment]
Hi @dstiliadis, thanks for the contribution. Was discussing these changes with @mdlayher, but haven't had the time to update this code base to his changes on master.

I see mdlayher/netlink also introduced vgo and I'm planning to follow suit. Give me a couple of days to sort it out.

**Comment by ti-mo** [comment]
Closed by #9
