### ISSUE TITLE
allow get/update of flows based only on the tupleReply

### ISSUE THREAD

**Issue by dstiliadis** [ti-mo/conntrack#11]
Hi @ti-mo 

In the current implementation updates/gets with a flow that has only the tupleReply defined are blocked by marshal and return an error. This is not required by the netlink API though. Even though for create both are needed, one can update a flow if only the tupleReply information is needed. This is useful when one only cares about the tupleReply state and not the original state.

I have a PR where this seems to work, but I was wondering if there is some other reason for 
that choice that I am missing.

Do you see any issues with that? If not, I can create PR.

**Comment by ti-mo** [comment]
Hi @dstiliadis

Thanks, I wasn't aware of that! There's no reason for this other than the fact that it didn't make sense to me to allow this at the time. In hindsight, it makes sense that any reply tuple in a stateful firewall is probably unique. Are you sure there cannot be collisions?

I'd love to see a use case/example so it can be added to the integration suite. :+1: Feel free to make a PR!

**Comment by ti-mo** [comment]
Hi @dstiliadis, any movement here?

**Comment by dstiliadis** [comment]
got stack with some things and forgot it. Let me get back to this towards
the weekend. Need to clean up the PR and add some tests.

**Comment by ti-mo** [comment]
This still needs integration tests.
