### ISSUE TITLE
Register()

### ISSUE THREAD

**Issue by eay** [ti-mo/conntrack#12]
I'm playing with implementing a conntrack(1) clone on top of your package, and using Register(), I'm not seeing ct.NetlinkCtDestroy NetlinkGroup events.
New and Update, yes, Destroy no.

Digger further, I belive it is an issue in the use of 
return os.NewSyscallError("setsockopt", c.s.SetSockoptInt(
                unix.SOL_NETLINK,
                unix.NETLINK_ADD_MEMBERSHIP,
                int(group),
        ))      
in conn_linux.go function JoinGroup.
I belivethe problem is that the setsockoptInt() version of group is not a bitmask value, as defined in 
linux/netfilter/nfnetlink_compat.h, but rather the values defined in
enum nfnetlink_groups in linux/netfilter/nfnetlink.h.
You are calling setsockopt once for each group, but the bitmask values of
1, 2, 4, 8, 16, 32 are not registering 3, which is the enum for NFNLGRP_CONNTRACK_DESTROY.

I've done an evil hack of
        group = uint32(bits.TrailingZeros8(uint8(group)) + 1)
around JoinGroup/LeaveGroup
seems to let me get events but no data.  len(Conn) == 0

**Comment by eay** [comment]
Woops, I've been looking at a few different conntrack libraries and this bug was meant for a different window/library, many apologies. (I'm trying to see how I delete the issue)

**Comment by ti-mo** [comment]
@eay No worries, was wondering why this didn't work for you, since I remember using this functionality in conntracct. (now replaced with eBPF)
