### ISSUE TITLE
Allow walking the message without a full unmarshal?

### ISSUE THREAD

**Issue by smarterclayton** [ti-mo/conntrack#13]
I'm using conntrack (thanks!) for doing some fairly simple monitoring of dropped connections and was looking for ways to reduce garbage / CPU spent in GC for flows where only a few attributes were being called.  I wanted to specifically defer full unmarshal in the event that a few basic criteria weren't met (protocol, port, flow status, etc).  Would you consider an API addition to conntrack/netfilter that allows walking the message without fully decoding?

As an example of the structure I was using in a fork:

```
		ok, err := netfilter.WalkMessage(
			recv[0],
			func(h netfilter.Header) (bool, error) {
				if h.SubsystemID != netfilter.NFSubsysCTNetlink {
					return false, nil
				}
				if err := event.Type.Unmarshal(h); err != nil {
					return false, err
				}
				switch event.Type {
				case conntrack.EventDestroy, conntrack.EventUpdate:
					return true, nil
				default:
					return false, nil
				}
			},
			func(attr netfilter.Attribute) (bool, error) {
				switch conntrack.AttributeType(attr.Type) {
				case conntrack.CTAStatus:
					if event.Type != conntrack.EventDestroy {
						return true, nil
					}
					if err := flow.Unmarshal([]netfilter.Attribute{attr}); err != nil {
						return false, err
					}
					if flow.Status.SeenReply() {
						return false, nil
					}
				case conntrack.CTATupleOrig:
					if err := attr.UnmarshalNested(); err != nil {
						return false, err
					}
					if err := flow.Unmarshal([]netfilter.Attribute{attr}); err != nil {
						return false, err
					}
					if flow.TupleOrig.Proto.Protocol != unix.IPPROTO_TCP {
						return false, nil
					}
				}
				return true, nil
			},
		)
```

and the implementations might look like:

```
// WalkMessage unmarshals a netlink.Message into a Netfilter Header and Attributes.
func WalkMessage(msg netlink.Message, hdrFn func(Header) (bool, error), attrFn func(Attribute) (bool, error)) (bool, error) {
	var h Header
	err := h.unmarshal(msg)
	if err != nil {
		return false, err
	}
	ok, err := hdrFn(h)
	if err != nil {
		return false, err
	}
	if !ok {
		return false, nil
	}
	return WalkAttributes(msg.Data[nfHeaderLen:], attrFn)
}

// WalkAttributes steps through a net link message, invoking fn
// once per Attribute structure.
func WalkAttributes(b []byte, fn func(Attribute) (bool, error)) (bool, error) {
	// Obtain a list of parsed netlink attributes possibly holding
	// nested Netfilter attributes in their binary Data field.
	attrs, err := netlink.UnmarshalAttributes(b)
	if err != nil {
		return false, errors.Wrap(err, errWrapNetlinkUnmarshalAttrs)
	}

	for _, nla := range attrs {
		// Copy the netlink attribute's fields into the netfilter attribute.
		nfa := Attribute{
			// Only consider the rightmost 14 bits for Type
			Type: nla.Type & ^(uint16(unix.NLA_F_NESTED) | uint16(unix.NLA_F_NET_BYTEORDER)),
			Data: nla.Data,
		}

		// Boolean flags extracted from the two leftmost bits of Type
		nfa.Nested = (nla.Type & uint16(unix.NLA_F_NESTED)) != 0
		nfa.NetByteOrder = (nla.Type & uint16(unix.NLA_F_NET_BYTEORDER)) != 0

		if nfa.NetByteOrder && nfa.Nested {
			return false, errInvalidAttributeFlags
		}

		ok, err := fn(nfa)
		if err != nil {
			return false, err
		}
		if !ok {
			return false, nil
		}
	}

	return true, nil
}
```

This does require public access to some of the constants and unmarshal methods to make practical - is that something you'd be willing to accept a PR for?  I had planned on raising a similar ask to mdlayher/netlink to allow the attributes to be walked instead of allocated, but even without that I was able to cut allocations by 90% for the core loop.

**Comment by ti-mo** [comment]
Hi @smarterclayton 

This abstraction already exists in mdlayher/netlink as `AttributeEncoder` and `AttributeDecoder`. In `netfilter` and `conntrack`, I try to copy the interface of `netlink` (which in turn copies the stdlib) as closely as possible, but I haven't had the bandwidth to adopt this convention yet. (my packages are 100% side projects) When these libraries were created, `*Encoder/Decoder` did not yet exist.

The efficiency gains would be large, as there are multiple levels of unmarshaling and allocations that can be eliminated. `conntrack` would call into `netfilter`'s codec, which needs to take care of nesting. The netfilter family of protocols has its own attribute nesting convention (the `nfgenmsg`), completely separate from the netlink convention. `netfilter` would then call into `netlink`'s codec. Both packages would need their codecs implemented and their constants exposed.

In a later stage, we would completely avoid any intermediate marshals/unmarshals, but that doesn't need to be done right off the bat.

PRs are absolutely welcome, of course. Please get in touch on Gophers Slack #networking (or DMs) if you need synchronous comms.

**Comment by ti-mo** [comment]
Closing this as I'm not planning to work on this, and looks like the author (and OpenShift) moved on long ago.
