### ISSUE TITLE
Counter unmarshaling fails if nf_conntrack_helper is enabled 

### ISSUE THREAD

**Issue by jamesbo13** [ti-mo/conntrack#15]
Compiling on MIPS for my OpenWRT router discovered that conntrack flows were not being decoded properly.  Attempting to print counters for flows returned by `Dump()` resulted in the following error:
```
need exactly 2 child attributes for attribute type ctaCountersOrig/ctaCountersReply
```

The issue is that my router has `nf_conntrack_helper` set to 'N' rather than default 0. (Why OpenWRT is setting this value rather than '1' I'm not sure): 
```
root@router:~# cat /sys/module/nf_conntrack/parameters/nf_conntrack_helper 
N
```

When enabled, this embeds 2 additional attributes into the Children slice, causing the check of number of children in `(*Counter) unmarshal()` to fail. A small change to the function to allow more children and to ignore any of type `ctaHelp` allows unmarshaling to complete without error.

**Comment by jamesbo13** [comment]
Opened PR https://github.com/ti-mo/conntrack/pull/16

**Comment by ti-mo** [comment]
Hi @jamesbo13, thanks for the report! According to [the documentation](https://www.kernel.org/doc/Documentation/networking/nf_conntrack-sysctl.txt), any non-0 value will enable this feature.

The PR's a good start, but Looks like the unmarshaler needs to
