### ISSUE TITLE
Feature: change buffer size of netfilter socket

### ISSUE THREAD

**Issue by MarkusBauer** [ti-mo/conntrack#21]
Hi, 
I recently used this module on a high-bandwidth server and got regular crashes because the netlink socket buffer was filled up. To counter this issue I would like to increase the buffer size of the underlying netlink socket, but conntrack does not provide the necessary methods yet. 

I'm willing to implement this feature and send a PR if I get some guidance from the author.

The used [netlink package](https://github.com/mdlayher/netlink) already has a method to change the buffer size: [netlink.Conn.SetReadBuffer](https://godoc.org/github.com/mdlayher/netlink#Conn.SetReadBuffer), so I see two possible solutions:

1. `conntrack.Conn` could itself has a method `SetReadBuffer` which in turn calls a new `SetReadBuffer` method on `netfilter.Conn`, which in turn calls this method on `netlink.Conn`. 
2. `conntrack.Conn` somehow exposes the underlying `netlink.Conn` connection so that users can change this (and possibly other) parameters on the netlink connection. 

What would be the easiest and cleanest possibility to change a netlink socket's buffer size?

**Comment by MarkusBauer** [comment]
I just found [this fork](https://github.com/zjj2wry/conntrack) which already implements `SetReadBuffer` (see [this commit](https://github.com/zjj2wry/conntrack/commit/75c1cfcb4b55babbbbc59f0bea4be699896cd1f3)). Is it possible to merge that implementation?

**Comment by ti-mo** [comment]
@MarkusBauer Thanks for the issue, sorry for the delayed response.

I'll expose netlink's `SetReadBuffer` in this package's API. It's been in the back of my mind for a while, but never got around to it. I remember seeing that fork a while back, but they never got around to making a PR.

Give me a couple of days to iron this out.

**Comment by ti-mo** [comment]
Closed by #22.
