### ISSUE TITLE
Marshal Label attribute to update label of conntrack

### ISSUE THREAD

**Issue by jiho-jung** [ti-mo/conntrack#26]
Marshaling Label and LabelMask attributes are needed when `Conn.Update` try to change the Label of Conntrack
Here are my changes: 

```
diff --git a/flow.go b/flow.go
index 07617f1..a1b3c35 100644
--- a/flow.go
+++ b/flow.go
@@ -267,6 +267,18 @@ func (f Flow) marshal() ([]netfilter.Attribute, error) {
                attrs = append(attrs, f.SynProxy.marshal())
        }

+       if len(f.Labels) > 0 {
+               a := netfilter.Attribute{Type: uint16(ctaLabels)}
+               a.Data = f.Labels
+               attrs = append(attrs, a)
+       }
+
+       if len(f.LabelsMask) > 0 {
+               a := netfilter.Attribute{Type: uint16(ctaLabelsMask)}
+               a.Data = f.LabelsMask
+               attrs = append(attrs, a)
+       }
+
```

**Comment by ti-mo** [comment]
Hi @jiho-jung, please send patches as pull requests.

Have you been able to use labels successfully? When creating a Flow with Labels(Mask) set, a subsequent Get() doesn't contain the label. No luck through the `conntrack` CLI either, `--label-add xyz` doesn't seem to work even after setting up `/etc/xtables/connlabel.conf`, it just returns `Operation failed: No space left on device`.

**Comment by jiho-jung** [comment]
Hi,

Yes, I had. But I don't use iptables or nftables to create conntracks, use OpenvSwitch which allocates the label memory

I guess the label needs the chunk memory to store its data, but cannot be done through netlink.

Iptables is working well on CentOS 8.3 and then the label can be updated through netlink.
Here is an example using iptables:
```
# cat /etc/xtables/connlabel.conf
0    eth0-in
1    eth0-out
2    ppp-in
3    ppp-out
4    bulk-traffic
5    interactive
6    bit-6

# sudo modprobe nfnetlink_acct 
# sudo iptables -I OUTPUT -m connlabel --label bit-6 --set
# sudo conntrack -L conntrack -p icmp  -o label

# sudo conntrack -L conntrack -p icmp  -o label
conntrack v1.4.4 (conntrack-tools): 0 flow entries have been shown.

### do ping 8.8.8.8 in other terminal

# sudo conntrack -L conntrack -p icmp  -o label
icmp     1 29 src=2.2.2.83 dst=8.8.8.8 type=8 code=0 id=3019 src=8.8.8.8 dst=2.2.2.83 type=0 code=0 id=3019 mark=0 secctx=system_u:object_r:unlabeled_t:s0 use=1 labels=bit-6
conntrack v1.4.4 (conntrack-tools): 1 flow entries have been shown.

```

**Comment by ti-mo** [comment]
Interesting. The ct's label extension is only populated (by `nf_ct_labels_ext_add()`) when there is at least one user of connlabels in the network namespace. Users call `nf_connlabels_get()`, which bumps the refcount at `net->ct.labels_used`. This means one of act_ct, xt_connlabel, nft_ct or openvswitch must have at least one rule loaded that interacts with connlabels in order for a connlabel to be allocated for a newly-created ct. Just loading the modules isn't enough.

I'm not going to go as far as setting all that up in the test suite just for being able to test labels. It's just an opaque binary attribute, I'll only add tests for the marshaler.
