### ISSUE TITLE
Error "ProtoInfoTCP unmarshal: need (at least) 2 child attributes" on Ubuntu 22.04

### ISSUE THREAD

**Issue by lubo-cruise** [ti-mo/conntrack#28]
When I upgraded my system from Ubuntu 20.04 to 22.04 I got the error "ProtoInfoTCP unmarshal: need (at least) 2 child attributes".
The received netlink msg is below
```
{{212 unknown(258) 0 0 0} [2 0 0 0 52 0 1 128 20 0 1 128 8 0 1 0 10 0 100 52 8 0 2 0 10 208 240 84 28 0 2 128 5 0 1 0 6 0 0 0 6 0 2 0 237 238 0 0 6 0 3 0 1 187 0 0 52 0 2 128 20 0 1 128 8 0 1 0 10 208 240 84 8 0 2 0 10 208 229 115 28 0 2 128 5 0 1 0 6 0 0 0 6 0 2 0 1 187 0 0 6 0 3 0 237 238 0 0 8 0 12 0 247 95 136 190 8 0 3 0 0 0 3 158 28 0 9 128 12 0 1 0 0 0 0 0 0 0 0 16 12 0 2 0 0 0 0 0 0 0 5 119 28 0 10 128 12 0 1 0 0 0 0 0 0 0 0 14 12 0 2 0 0 0 0 0 0 0 18 39 16 0 4 128 12 0 1 128 5 0 1 0 8 0 0 0]}
netlink msg header: <Subsystem: NFSubsysCTNetlink, Message Type: 2, Family: ProtoIPv4, Version: 0, ResourceID: 0>
```

Seems this check (https://github.com/ti-mo/conntrack/blob/master/attribute_types.go#L153) failed because the received data has TCP_STATE only.
Is it good to remove the check?

**Comment by ti-mo** [comment]
Hi @lubo-cruise, thanks for the issue. What was the tcp state you received? Interesting that a tcp state would be created without flags.

Always happy to take a patch if the reason is well-documented. Not much time to work on this and investigate by myself at the moment.

**Comment by lubo-cruise** [comment]
Hi @ti-mo, Thanks for the reply. Below is the ctaProtoInfo attribute, i can see that the length is 12, the type is 1 (ctaProtoInfoTCPState), not sure how to decode the payload
ad.type: 4, at: ctaProtoInfo, ad.len: 8, ad.bytes: [12 0 1 128 5 0 1 0 8 0 0 0]

**Comment by ti-mo** [comment]
The reason behind these checks is simple: to validate assumptions and avoid silent breakage. Without it, we'd now emit TCP Flows without flags, which still doesn't sound valid, and may break this package consumers' assumptions. This library isn't developed as part of the iproute2 project, so we're generally not notified of breakage as downstream consumers.

- What kind of CT event does this occur on? (new/update?)
- What does `conntrack -E` output for the same event?
- Please post some strace output.
