### ISSUE TITLE
Neither err channel nor events channels are closed

### ISSUE THREAD

**Issue by ruz** [ti-mo/conntrack#32]
Hello,

Not sure if it breaks backwards compatibility or not, but I believe that `eventWorker` function should close error channel with `defer`.

The same applies to events channel. It a bit harder to close correctly when all workers are done, but it's correct way to deal with channels. Writer closes channel.

**Comment by ti-mo** [comment]
@ruz I agree, what you're describing is the canonical way of dealing with channels. I'm hesitant to change the behaviour now, though. Shortly before you posted this, I merged https://github.com/ti-mo/conntrack/pull/29 that makes `Conn.Close()` wait for all workers to exit, allowing you to synchronize teardown a bit better.

I'll cut a release today that includes this.
