### ISSUE TITLE
ProtoInfoTCP unmarshal: need (at least) 2 child attributes

### ISSUE THREAD

**Issue by ahmetozer** [ti-mo/conntrack#33]
Hello 👋🏻 

When I use this library on kernel `5.10.178-162.673.amzn2.x86_64`  I don't get any issues but when I deploy on `5.15.0-1031-aws` library works but sometimes throws the below error and stops capturing the events.

```
ProtoInfoTCP unmarshal: need (at least) 2 child attributes
```

I logged packages with this library and conntrack at the same time and I noticed close is shown as an update on conntrack and may be this breaks lib.

```
 [UPDATE] tcp      6 60 SYN_RECV src=XXXX dst=172.17.0.2 sport=54558 dport=8080 src=172.17.0.2 dst=XXXX sport=8080 dport=54558
 [UPDATE] tcp      6 10 CLOSE src=XXXX dst=172.17.0.2 sport=54556 dport=8080 src=172.17.0.2 dst=XXXX sport=8080 dport=54556 [ASSURED]
 ```
 
 other close events
 
 ```
[DESTROY] tcp      6 CLOSE src=XXXX dst=172.17.0.2 sport=53256 dport=8080 src=172.17.0.2 dst=XXXX sport=8080 dport=53256 [ASSURED]
```

**Comment by SuryanathanP** [comment]
I see the same issue with kernel version 5.15.0-67-generic.

**Comment by ti-mo** [comment]
Don't currently have the energy to work on this, would you be willing to figure out why this happens and submit a PR?

**Comment by ti-mo** [comment]
@ahmetozer @SuryanathanP This was fixed in https://github.com/ti-mo/conntrack/pull/31, please give current master a try.
